# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
